2025-06-07 11:04:14,160 (66239/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-06-07 11:04:14,160 (66239/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-06-07 11:04:14,170 (66239/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/main.py", line 766, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/main.py", line 737, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 117, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "gouthamr" does not exist\n'
2025-06-15 10:17:02,995 (9078/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-06-15 10:17:02,995 (9078/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-06-15 10:17:03,008 (9078/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/main.py", line 766, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/main.py", line 737, in connect\n    pgexecute = PGExecute(\n        database,\n    ...<6 lines>...\n        **kwargs,\n    )\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 184, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 233, in connect\n    conn = psycopg.connect(conn_info)\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/psycopg/connection.py", line 117, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "gouthamr" does not exist\n'
2025-06-15 10:17:16,392 (9231/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-06-15 10:17:16,392 (9231/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-06-15 10:17:35,484 (9231/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) ls\n                                                                ^')
2025-06-15 10:17:35,487 (9231/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) ls\n                                                                ^\n'
2025-06-15 10:17:42,688 (9231/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) help', error: SyntaxError('syntax error at or near "help"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) help\n                                                                ^')
2025-06-15 10:17:42,689 (9231/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "help"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) help\n                                                                ^\n'
2025-06-15 10:24:06,760 (9231/MainThread) pgcli.pgexecute ERROR - sql: "EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) select * from public.product_master_fta where product_category ILIKE 'beer' LIMIT 1", error: UndefinedFunction("operator does not exist: integer ~~* unknown\nLINE 1: ... public.product_master_fta where product_category ILIKE 'bee...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.")
2025-06-15 10:24:06,761 (9231/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedFunction: operator does not exist: integer ~~* unknown\nLINE 1: ... public.product_master_fta where product_category ILIKE \'bee...\n                                                             ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\n'
2025-06-15 10:24:23,041 (9231/MainThread) pgcli.pgexecute ERROR - sql: "EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) select * from public.product_master_fta where product_category %ILIKE 'beer' LIMIT 1", error: UndefinedObject('type "ilike" does not exist\nLINE 1: ...public.product_master_fta where product_category %ILIKE \'bee...\n                                                             ^')
2025-06-15 10:24:23,043 (9231/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 406, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 460, in execute_normal_sql\n    cur.execute(split_sql)\n    ~~~~~~~~~~~^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/pgcli/pgexecute.py", line 91, in execute\n    super().execute(*args, **kwargs)\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.3.0/libexec/lib/python3.13/site-packages/psycopg/cursor.py", line 97, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: type "ilike" does not exist\nLINE 1: ...public.product_master_fta where product_category %ILIKE \'bee...\n                                                             ^\n'
2025-06-16 11:19:24,560 (81976/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-06-16 11:19:24,561 (81976/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2025-06-16 17:25:36,635 (53714/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2025-06-16 17:25:36,636 (53714/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
